apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: airplay
  name: airplay
  namespace: default
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: airplay
  template:
    metadata:
      labels:
        app: airplay
    spec:
      containers:
        - env:
            - name: AIR_DISCORDTOKEN
              value: ${AIR_DISCORDTOKEN}
            - name: AIR_OPENAITOKEN
              value: ${AIR_OPENAITOKEN}
          image: ghcr.io/trojan295/discord-airplay:latest
          name: airplay
          resources:
            requests:
              cpu: "200m"
              memory: "128Mi"
            limits:
              cpu: 2
              memory: "256Mi"
      restartPolicy: Always
